'''
Python file to import the constant variables
'''
import os

PROJECT_ID = "PROJECT_NAME"
COMPUTE_REGION = "COMPUTE_REGION"
BUCKET_NAME = "BUCKET_NAME"
DATASET_NAME = "DATASET_NAME"
OPTIMAL_AUGMENTATION = "True"
MODEL_NAME_PREFIX = "TRAINED_MODEL_NAME"
PUBSUB_VERIFICATION_TOKEN = 'PUBSUB_VERIFICATION_TOKEN_NAME'
PUBSUB_TOPIC = 'PUBSUB_TOPIC_NAME'
PUBSUB_SUBSCRIBER = 'PUBSUB_SUBSCRIBER_NAME'
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

